name: Clone Repository

on:
  push:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Clone Repository
        run: |
         rm -rf *
         git clone --depth 1 https://github.com/qwq233/Nullgram -b master nullgram
         cd nullgram && rm -rf .git && cd -
         ls nullgram
         git config user.name "Your Name"
         git config user.email "your.email@example.com"
         git add --all nullgram/*
         git commit -m "nullgram"
         git clone --depth 1 https://github.com/PreviousAlone/Nnngram -b main nnngram
         cd nnngram && rm -rf .git
         mkdir TMessagesProj/src/main/java/top
         mkdir TMessagesProj/src/main/java/top/qwq2333
         mkdir TMessagesProj/src/main/java/top/qwq2333/nullgram
         mv TMessagesProj/src/main/java/xyz/nextalone TMessagesProj/src/main/java/top/qwq2333/nullgram
         mkdir libs/ksp/src/main/kotlin/top
         mkdir libs/ksp/src/main/kotlin/top/qwq2333
         mkdir libs/ksp/src/main/kotlin/top/qwq2333/nullgram
         mv libs/ksp/src/main/kotlin/xyz/nextalone libs/ksp/src/main/kotlin/top/qwq2333/nullgram

         cd -
         ls nnngram
         cp -rf ./nnngram/. ./nullgram/
         rm -rf nnngram
         git status
         git config user.name "Your Name"
         git config user.email "your.email@example.com"
         git add --all nullgram/*
         git commit -m "nnngram"
         git push
