name: Clone Repository

on:
  push:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: |
         git clone https://github.com/qwq233/Nullgram -b main nullgram
         git clone https://github.com/PreviousAlone/Nnngram -b main nnngram
         mv nnngram/* nullgram/
         git config user.name "Your Name"
         git config user.email "your.email@example.com"
         git add .
         git commit -m "Compare repositories"
         git push origin main
