name: Clone Repository

on:
  push:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Clone Repository
        run: |
         rm -rf *
         git clone https://github.com/qwq233/Nullgram nullgram
         cd nullgram && rm -rf .git && cd -
         ls nullgram
         git clone https://github.com/PreviousAlone/Nnngram nnngram
         cd nnngram && rm -rf .git && cd -
         ls nnngram
         rm -rf nnngram
         git config user.name "Your Name"
         git config user.email "your.email@example.com"
         git status
         git add nullgram
         git commit -m "Compare repositories"
         git push
