name: Clone Repository

on:
  push:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Clone Repository
        run: |
         rm -rf *
         git clone --depth 1 https://github.com/qwq233/Nullgram -b master nullgram
         git clone --depth 1 https://github.com/PreviousAlone/Nnngram -b main nnngram
         git config user.name "Your Name"
         git config user.email "your.email@example.com"
         git status
         git add .
         git commit -m "Compare repositories"
         git push
